obj-$(CONFIG_CONDOR) += condor_dev.o \
                condor_netdev.o \
                condor_hw.o \
                condor_hw_radio.o \
                condor_channel.o \
                condor_tx.o \
                condor_dot11_tx.o \
				condor_netif.o \
				condor_queue.o \
				condor_thread.o \
				condor_tx_thread.o \
				condor_dot11_rx.o \
				condor_rx_thread.o

subdir-ccflags-y := $(INCLUDE)
